<span style="font-size: 24px;">Data Cleaning Start From Here</span>

In [5]:
import pandas as pd

ab_test = pd.read_csv("ab_test.csv")
ab_test.head(8)

  variant  sessions  clicks  orders
0       A        98      13       2
1       A       186      70      10
2       A       156      19       3
3       A       120      33       4
4       A       161      39       7
5       A        85      24       4
6       A        53      14       2
7       A       159      16       1

In [6]:
import pandas as pd
from pathlib import Path

for file in Path(".").glob("*.csv"):
    print(f"\n{'='*60}")
    print(f"File: {file.name}")
    
    df = pd.read_csv(file)
    
    print(f"Total rows: {df.shape[0]}")
    print(f"Total columns: {df.shape[1]}")
    
    print("\nColumn names:")
    print(df.columns.tolist())
    
    print("\nNull values:")
    print(df.isnull().sum())
    
    print("\nColumn types:")
    print(df.dtypes)
    
    print(f"\nDuplicate rows: {df.duplicated().sum()}")
    
    print("\nMessy / weird values check:")
    for col in df.columns:
        if df[col].dtype == "object":
            print(f"\nColumn: {col}")
            print("Unique sample values:")
            print(df[col].dropna().astype(str).str.strip().value_counts().head(10))

============================================================
File: ab_test.csv
Total rows: 2000
Total columns: 4

Column names:
['variant', 'sessions', 'clicks', 'orders']

Null values:
variant     0
sessions    0
clicks      0
orders      0
dtype: int64

Column types:
variant       str
sessions    int64
clicks      int64
orders      int64
dtype: object

Duplicate rows: 64

Messy / weird values check:

============================================================
File: add_to_cart.csv
Total rows: 1019
Total columns: 3

Column names:
['session_id', 'product_id', 'timestamp']

Null values:
session_id    0
product_id    0
timestamp     0
dtype: int64

Column types:
session_id    str
product_id    str
timestamp     str
dtype: object

Duplicate rows: 0

Messy / weird values check:

============================================================
File: checkout.csv
Total rows: 610
Total columns: 2

Column names:
['session_id', 'timestamp']

Null values:
session_id    0
timestamp     0
dtype: int64

Column types:
session_id    str
timestamp     str
dtype: object

Duplicate rows: 0

Messy / weird values check:

============================================================
File: dashboard.csv
Total rows: 500
Total columns: 7

Column names:
['category', 'CTR', 'BounceRate', 'ConversionRate', 'AOV', 'ReturningUsersPct', 'Revenue']

Null values:
category             0
CTR                  0
BounceRate           0
ConversionRate       0
AOV                  0
ReturningUsersPct    0
Revenue              0
dtype: int64

Column types:
category                 str
CTR                  float64
BounceRate           float64
ConversionRate       float64
AOV                  float64
ReturningUsersPct    float64
Revenue              float64
dtype: object

Duplicate rows: 0

Messy / weird values check:

============================================================
File: heatmap.csv
Total rows: 1400
Total columns: 5

Column names:
['page', 'avg_scroll_depth', 'rage_clicks', 'avg_time_on_page', 'exit_rate']

Null values:
page                0
avg_scroll_depth    0
rage_clicks         0
avg_time_on_page    0
exit_rate           0
dtype: int64

Column types:
page                    str
avg_scroll_depth    float64
rage_clicks           int64
avg_time_on_page    float64
exit_rate           float64
dtype: object

Duplicate rows: 0

Messy / weird values check:

============================================================
File: orders.csv
Total rows: 438
Total columns: 4

Column names:
['session_id', 'order_id', 'revenue', 'timestamp']

Null values:
session_id    0
order_id      0
revenue       0
timestamp     0
dtype: int64

Column types:
session_id        str
order_id          str
revenue       float64
timestamp         str
dtype: object

Duplicate rows: 0

Messy / weird values check:

============================================================
File: page_views.csv
Total rows: 6024
Total columns: 4

Column names:
['session_id', 'product_id', 'category', 'timestamp']

Null values:
session_id    0
product_id    0
category      0
timestamp     0
dtype: int64

Column types:
session_id    str
product_id    str
category      str
timestamp     str
dtype: object

Duplicate rows: 0

Messy / weird values check:

In [7]:
import pandas as pd

ab_test = pd.read_csv('ab_test.csv')

initial_count = len(ab_test)

ab_test_cleaned = ab_test.drop_duplicates()

removed_count = initial_count - len(ab_test_cleaned)
print(f"Removed {removed_count} duplicate rows.")

ab_test_cleaned.to_csv('ab_test_cleaned.csv', index=False)

Removed 64 duplicate rows.

<span style="font-size: 16px;">I found 64 duplicate rows and removed them.</span>

In [8]:
import pandas as pd

add_to_cart = pd.read_csv("add_to_cart.csv")
add_to_cart.head(7)

  session_id product_id            timestamp
0     S00002      P0270  2025-09-03 13:36:00
1     S00004      P0022  2025-09-05 19:41:00
2     S00005      P0072  2025-09-03 15:28:00
3     S00008      P0205  2025-09-01 01:31:00
4     S00010      P0117  2025-09-06 15:28:00
5     S00011      P0086  2025-09-02 17:53:00
6     S00012      P0087  2025-09-07 05:50:00

In [9]:
print("Total rows:", add_to_cart.shape[0])
print("Total columns:", add_to_cart.shape[1])

print("\nData types:")
print(add_to_cart.dtypes)

print("\nNull values:")
print(add_to_cart.isnull().sum())

print("\nDuplicate rows:", add_to_cart.duplicated().sum())

print("\nWeird values check:")
for col in add_to_cart.columns:
    if add_to_cart[col].dtype == "object":
        print(f"\nColumn: {col}")
        print(add_to_cart[col].value_counts().head(10))

Total rows: 1019
Total columns: 3

Data types:
session_id    str
product_id    str
timestamp     str
dtype: object

Null values:
session_id    0
product_id    0
timestamp     0
dtype: int64

Duplicate rows: 0

Weird values check:

In [10]:
add_to_cart["timestamp"] = pd.to_datetime(add_to_cart["timestamp"])
add_to_cart["add_to_cart_date"] = add_to_cart["timestamp"].dt.date
add_to_cart["add_to_cart_time"] = add_to_cart["timestamp"].dt.time

In [11]:
add_to_cart.head(7)

  session_id product_id           timestamp add_to_cart_date add_to_cart_time
0     S00002      P0270 2025-09-03 13:36:00       2025-09-03         13:36:00
1     S00004      P0022 2025-09-05 19:41:00       2025-09-05         19:41:00
2     S00005      P0072 2025-09-03 15:28:00       2025-09-03         15:28:00
3     S00008      P0205 2025-09-01 01:31:00       2025-09-01         01:31:00
4     S00010      P0117 2025-09-06 15:28:00       2025-09-06         15:28:00
5     S00011      P0086 2025-09-02 17:53:00       2025-09-02         17:53:00
6     S00012      P0087 2025-09-07 05:50:00       2025-09-07         05:50:00

In [12]:
add_to_cart["add_to_cart_time"] = pd.to_datetime(add_to_cart["add_to_cart_time"], format="%H:%M:%S").dt.strftime("%I:%M %p")
add_to_cart = add_to_cart.drop(columns=["timestamp"])
add_to_cart.head(7)

  session_id product_id add_to_cart_date add_to_cart_time
0     S00002      P0270       2025-09-03         01:36 PM
1     S00004      P0022       2025-09-05         07:41 PM
2     S00005      P0072       2025-09-03         03:28 PM
3     S00008      P0205       2025-09-01         01:31 AM
4     S00010      P0117       2025-09-06         03:28 PM
5     S00011      P0086       2025-09-02         05:53 PM
6     S00012      P0087       2025-09-07         05:50 AM

In [13]:
add_to_cart.to_csv(r"D:\Rokomari_Cleaned\add_to_cart_cleaned.csv", index=False)

<span style="font-size: 16px;">I extracted the date and time from the timestamp column.</span>

In [14]:
checkout = pd.read_csv("checkout.csv")
checkout.head(7)

  session_id            timestamp
0     S00002  2025-09-03 01:17:00
1     S00004  2025-09-05 08:09:00
2     S00005  2025-09-03 14:39:00
3     S00011  2025-09-02 18:47:00
4     S00012  2025-09-06 14:35:00
5     S00014  2025-09-06 02:57:00
6     S00015  2025-09-01 13:50:00

In [15]:
print(f"Total Carts: {add_to_cart['session_id'].nunique()}")
print(f"Total Checkouts: {checkout['session_id'].nunique()}")

Total Carts: 1019
Total Checkouts: 610

In [16]:
print("Total rows:", checkout.shape[0])
print("Total columns:", checkout.shape[1])

print("\nData types:")
print(checkout.dtypes)

print("\nNull values:")
print(checkout.isnull().sum())

print("\nDuplicate rows:", checkout.duplicated().sum())

print("\nWeird values check:")
for col in checkout.columns:
    if checkout[col].dtype == "object":
        print(f"\nColumn: {col}")
        print(checkout[col].value_counts().head(10))

Total rows: 610
Total columns: 2

Data types:
session_id    str
timestamp     str
dtype: object

Null values:
session_id    0
timestamp     0
dtype: int64

Duplicate rows: 0

Weird values check:

In [17]:
checkout["timestamp"] = pd.to_datetime(checkout["timestamp"])
checkout["checkout_date"] = checkout["timestamp"].dt.date
checkout["checkout_time"] = checkout["timestamp"].dt.strftime("%I:%M %p")
checkout = checkout.drop(columns=["timestamp"])
checkout.head(7)

  session_id checkout_date checkout_time
0     S00002    2025-09-03      01:17 AM
1     S00004    2025-09-05      08:09 AM
2     S00005    2025-09-03      02:39 PM
3     S00011    2025-09-02      06:47 PM
4     S00012    2025-09-06      02:35 PM
5     S00014    2025-09-06      02:57 AM
6     S00015    2025-09-01      01:50 PM

In [18]:
checkout.to_csv(r"D:\Rokomari_Cleaned\checkout_cleaned.csv", index=False)

In [19]:
dashboard = pd.read_csv("dashboard.csv")
dashboard.head(7)

,category,CTR,BounceRate,ConversionRate,AOV,ReturningUsersPct,Revenue
0,Books,4.952534,32.270379,1.134470,1034.006493,21.184607,131439.515674
1,Books,4.876201,76.790360,1.539964,505.075618,38.036964,121487.684762
2,Books,3.480125,64.489456,3.204308,434.103604,49.507899,25108.265060
3,Books,0.589967,66.179492,2.967608,1138.309702,29.137366,12107.573770
4,Books,1.989569,56.488114,1.515664,1125.365200,49.720050,96310.729689
5,Books,4.440746,71.288994,4.451261,1093.244439,25.239450,101437.743651
6,Books,3.697298,32.633819,3.824796,957.706341,14.800872,115884.402130

In [24]:
import pandas as pd

# Load dashboard file
dashboard = pd.read_csv("dashboard.csv")

# ==============================
# Basic dataset info
# ==============================
print("=" * 60)
print("DASHBOARD DATA CHECK")
print("=" * 60)

print(f"Total rows: {dashboard.shape[0]}")
print(f"Total columns: {dashboard.shape[1]}")

print("\nColumn names:")
print(dashboard.columns.tolist())

# ==============================
# Data type of each column
# ==============================
print("\n" + "=" * 60)
print("COLUMN DATA TYPES")
print("=" * 60)
for col in dashboard.columns:
    print(f"{col} : {dashboard[col].dtype}")

# ==============================
# Column-wise total rows, non-null, null
# ==============================
print("\n" + "=" * 60)
print("COLUMN-WISE DETAILS")
print("=" * 60)
for col in dashboard.columns:
    total_rows = len(dashboard[col])
    non_null = dashboard[col].notnull().sum()
    null_count = dashboard[col].isnull().sum()

    print(f"\nColumn: {col}")
    print(f"Data type: {dashboard[col].dtype}")
    print(f"Total rows: {total_rows}")
    print(f"Non-null values: {non_null}")
    print(f"Null values: {null_count}")

# ==============================
# Check if any null exists
# ==============================
print("\n" + "=" * 60)
print("NULL CHECK")
print("=" * 60)

if dashboard.isnull().values.any():
    print("Yes, there are null values.")
    print("\nNull values per column:")
    print(dashboard.isnull().sum())
else:
    print("No null values found.")

# ==============================
# Check duplicates
# ==============================
print("\n" + "=" * 60)
print("DUPLICATE CHECK")
print("=" * 60)

duplicate_count = dashboard.duplicated().sum()
print(f"Duplicate rows: {duplicate_count}")

if duplicate_count > 0:
    print("Yes, duplicate rows exist.")
else:
    print("No duplicate rows found.")

# ==============================
# Weird / messy values check
# ==============================
print("\n" + "=" * 60)
print("WEIRD / MESSY VALUES CHECK")
print("=" * 60)

for col in dashboard.columns:
    if dashboard[col].dtype == "object":
        print(f"\nColumn: {col}")
        print("Top 10 values:")
        print(
            dashboard[col]
            .dropna()
            .astype(str)
            .str.strip()
            .value_counts()
            .head(10)
        )

# ==============================
# Optional: preview first 7 rows
# ==============================
print("\n" + "=" * 60)
print("FIRST 7 ROWS")
print("=" * 60)
print(dashboard.head(7))

============================================================
DASHBOARD DATA CHECK
============================================================
Total rows: 500
Total columns: 7

Column names:
['category', 'CTR', 'BounceRate', 'ConversionRate', 'AOV', 'ReturningUsersPct', 'Revenue']

============================================================
COLUMN DATA TYPES
============================================================
category : str
CTR : float64
BounceRate : float64
ConversionRate : float64
AOV : float64
ReturningUsersPct : float64
Revenue : float64

============================================================
COLUMN-WISE DETAILS
============================================================

Column: category
Data type: str
Total rows: 500
Non-null values: 500
Null values: 0

Column: CTR
Data type: float64
Total rows: 500
Non-null values: 500
Null values: 0

Column: BounceRate
Data type: float64
Total rows: 500
Non-null values: 500
Null values: 0

Column: ConversionRate
Data type: float64
Total rows: 500
Non-null values: 500
Null values: 0

Column: AOV
Data type: float64
Total rows: 500
Non-null values: 500
Null values: 0

Column: ReturningUsersPct
Data type: float64
Total rows: 500
Non-null values: 500
Null values: 0

Column: Revenue
Data type: float64
Total rows: 500
Non-null values: 500
Null values: 0

============================================================
NULL CHECK
============================================================
No null values found.

============================================================
DUPLICATE CHECK
============================================================
Duplicate rows: 0
No duplicate rows found.

============================================================
WEIRD / MESSY VALUES CHECK
============================================================

============================================================
FIRST 7 ROWS
============================================================
  category       CTR  BounceRate  ConversionRate          AOV  ReturningUsersPct        Revenue
0    Books  4.952534   32.270379        1.134470  1034.006493          21.184607  131439.515674
1    Books  4.876201   76.790360        1.539964   505.075618          38.036964  121487.684762
2    Books  3.480125   64.489456        3.204308   434.103604          49.507899   25108.265060
3    Books  0.589967   66.179492        2.967608  1138.309702          29.137366   12107.573770
4    Books  1.989569   56.488114        1.515664  1125.365200          49.720050   96310.729689
5    Books  4.440746   71.288994        4.451261  1093.244439          25.239450  101437.743651
6    Books  3.697298   32.633819        3.824796   957.706341          14.800872  115884.402130

In [26]:
import pandas as pd

df = pd.read_csv("dashboard.csv")

print("Total rows:", df.shape[0])
print("Total columns:", df.shape[1])

print("\nColumn types:")
print(df.dtypes)

print("\nNon-null count per column:")
print(df.notnull().sum())

print("\nNull count per column:")
print(df.isnull().sum())

print("\nAny null values?")
print("Yes" if df.isnull().any().any() else "No")

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nWeird / messy values:")
for col in df.columns:
    if df[col].dtype == "object":
        print(f"\nColumn: {col}")
        print(df[col].astype(str).str.strip().value_counts().head(10))

Total rows: 500
Total columns: 7

Column types:
category                 str
CTR                  float64
BounceRate           float64
ConversionRate       float64
AOV                  float64
ReturningUsersPct    float64
Revenue              float64
dtype: object

Non-null count per column:
category             500
CTR                  500
BounceRate           500
ConversionRate       500
AOV                  500
ReturningUsersPct    500
Revenue              500
dtype: int64

Null count per column:
category             0
CTR                  0
BounceRate           0
ConversionRate       0
AOV                  0
ReturningUsersPct    0
Revenue              0
dtype: int64

Any null values?
No

Duplicate rows:
0

Weird / messy values:

In [27]:
import pandas as pd

dashboard = pd.read_csv("dashboard.csv")

cols_to_fix = ["CTR", "BounceRate", "ConversionRate", "AOV", "ReturningUsersPct", "Revenue"]
dashboard[cols_to_fix] = dashboard[cols_to_fix].round(2)

dashboard["category"] = dashboard["category"].str.strip()

print(dashboard.head())

  category   CTR  BounceRate  ConversionRate      AOV  ReturningUsersPct    Revenue
0    Books  4.95       32.27            1.13  1034.01              21.18  131439.52
1    Books  4.88       76.79            1.54   505.08              38.04  121487.68
2    Books  3.48       64.49            3.20   434.10              49.51   25108.27
3    Books  0.59       66.18            2.97  1138.31              29.14   12107.57
4    Books  1.99       56.49            1.52  1125.37              49.72   96310.73

In [28]:
import os

output_folder = r"D:\Rokomari_Cleaned"
os.makedirs(output_folder, exist_ok=True)

dashboard.to_csv(r"D:\Rokomari_Cleaned\dashboard_cleaned.csv", index=False)
print("Cleaned file saved successfully.")

Cleaned file saved successfully.

In [29]:
import pandas as pd

heatmap = pd.read_csv("heatmap.csv")
print(heatmap.head(10))

       page  avg_scroll_depth  rage_clicks  avg_time_on_page  exit_rate
0  Homepage         49.568149            6         87.421639  66.390142
1  Homepage         94.331612            0         35.311066  63.267432
2  Homepage         59.860062            1         79.769456  49.902645
3  Homepage         72.771425            4         42.173380  75.672821
4  Homepage         25.745218            6          8.583671  28.992613
5  Homepage         36.365981            0         46.281599  47.736230
6  Homepage         79.757965            8         35.112811  76.732551
7  Homepage         28.305247            9         10.467975  54.885049
8  Homepage         24.832822            6         47.172398  41.645360
9  Homepage         31.773380            8         26.044737  40.711605

In [30]:
import pandas as pd

heatmap = pd.read_csv("heatmap.csv")

print("Total rows:", heatmap.shape[0])
print("Total columns:", heatmap.shape[1])

print("\nColumn types:")
print(heatmap.dtypes)

print("\nNull values:")
print(heatmap.isnull().sum())

print("\nAny null values?")
print("Yes" if heatmap.isnull().any().any() else "No")

print("\nDuplicate rows:")
print(heatmap.duplicated().sum())

print("\nMessy / weird words:")
for col in heatmap.columns:
    if heatmap[col].dtype == "object":
        print(f"\nColumn: {col}")
        print(heatmap[col].astype(str).str.strip().value_counts().head(10))

Total rows: 1400
Total columns: 5

Column types:
page                    str
avg_scroll_depth    float64
rage_clicks           int64
avg_time_on_page    float64
exit_rate           float64
dtype: object

Null values:
page                0
avg_scroll_depth    0
rage_clicks         0
avg_time_on_page    0
exit_rate           0
dtype: int64

Any null values?
No

Duplicate rows:
0

Messy / weird words:

In [31]:
import pandas as pd
import os

heatmaps = pd.read_csv("heatmap.csv")

heatmaps["avg_scroll_depth"] = heatmaps["avg_scroll_depth"].round(2)
heatmaps["avg_time_on_page"] = heatmaps["avg_time_on_page"].round(2)
heatmaps["exit_rate"] = heatmaps["exit_rate"].round(2)

heatmaps["page"] = heatmaps["page"].str.strip()

heatmaps["rage_clicks"] = heatmaps["rage_clicks"].astype(int)

os.makedirs("cleaned", exist_ok=True)
heatmaps.to_csv("cleaned/heatmap_cleaned.csv", index=False)

print("Heatmap Cleaning Complete!")
print(heatmaps.head())

Heatmap Cleaning Complete!
       page  avg_scroll_depth  rage_clicks  avg_time_on_page  exit_rate
0  Homepage             49.57            6             87.42      66.39
1  Homepage             94.33            0             35.31      63.27
2  Homepage             59.86            1             79.77      49.90
3  Homepage             72.77            4             42.17      75.67
4  Homepage             25.75            6              8.58      28.99

In [32]:
import pandas as pd
import os

heatmaps = pd.read_csv("heatmap.csv")

heatmaps["avg_scroll_depth"] = heatmaps["avg_scroll_depth"].round(2)
heatmaps["avg_time_on_page"] = heatmaps["avg_time_on_page"].round(2)
heatmaps["exit_rate"] = heatmaps["exit_rate"].round(2)

heatmaps["page"] = heatmaps["page"].str.strip()
heatmaps["rage_clicks"] = heatmaps["rage_clicks"].astype(int)

os.makedirs(r"D:\Rokomari_Cleaned", exist_ok=True)
heatmaps.to_csv(r"D:\Rokomari_Cleaned\heatmap_cleaned.csv", index=False)

print("Heatmap Cleaning Complete!")
print(heatmaps.head())

Heatmap Cleaning Complete!
       page  avg_scroll_depth  rage_clicks  avg_time_on_page  exit_rate
0  Homepage             49.57            6             87.42      66.39
1  Homepage             94.33            0             35.31      63.27
2  Homepage             59.86            1             79.77      49.90
3  Homepage             72.77            4             42.17      75.67
4  Homepage             25.75            6              8.58      28.99

In [33]:
heatmaps.to_csv(r"D:\Rokomari_Cleaned\heatmap_cleaned.csv", index=False)
print("Saved in D:\\Rokomari_Cleaned")

Saved in D:\Rokomari_Cleaned

In [34]:
import pandas as pd

orders = pd.read_csv("orders.csv")
print(orders.head(10))

  session_id order_id  revenue            timestamp
0     S00002   O27643  1508.52  2025-09-04 21:50:00
1     S00004   O45525   705.59  2025-09-02 18:49:00
2     S00011   O30238  1700.37  2025-09-02 01:06:00
3     S00012   O74313  1877.89  2025-09-05 14:42:00
4     S00014   O72662  1200.51  2025-09-04 01:09:00
5     S00015   O15317  1124.57  2025-09-01 02:51:00
6     S00022   O59456   622.01  2025-09-03 11:37:00
7     S00027   O93447  1702.02  2025-09-06 20:37:00
8     S00036   O85980  1156.51  2025-09-06 05:28:00
9     S00038   O35889   588.69  2025-09-02 06:10:00

In [35]:
import pandas as pd

orders = pd.read_csv("orders.csv")

print("Total rows:", orders.shape[0])
print("Total columns:", orders.shape[1])

print("\nColumn types:")
print(orders.dtypes)

print("\nNull values:")
print(orders.isnull().sum())

print("\nAny null values?")
print("Yes" if orders.isnull().any().any() else "No")

print("\nDuplicate rows:")
print(orders.duplicated().sum())

print("\nMessy / weird words:")
for col in orders.columns:
    if orders[col].dtype == "object":
        print(f"\nColumn: {col}")
        print(orders[col].astype(str).str.strip().value_counts().head(10))

Total rows: 438
Total columns: 4

Column types:
session_id        str
order_id          str
revenue       float64
timestamp         str
dtype: object

Null values:
session_id    0
order_id      0
revenue       0
timestamp     0
dtype: int64

Any null values?
No

Duplicate rows:
0

Messy / weird words:

In [37]:
import pandas as pd

orders = pd.read_csv("orders.csv")

orders["order_date"] = pd.to_datetime(orders["timestamp"]).dt.date
orders["order_time"] = pd.to_datetime(orders["timestamp"]).dt.strftime("%I:%M %p")

orders = orders.drop(columns=["timestamp"])

print(orders.head())

  session_id order_id  revenue  order_date order_time
0     S00002   O27643  1508.52  2025-09-04   09:50 PM
1     S00004   O45525   705.59  2025-09-02   06:49 PM
2     S00011   O30238  1700.37  2025-09-02   01:06 AM
3     S00012   O74313  1877.89  2025-09-05   02:42 PM
4     S00014   O72662  1200.51  2025-09-04   01:09 AM

In [38]:
orders.to_csv(r"D:\Rokomari_Cleaned\orders_cleaned.csv", index=False)
print("Saved in D:\\Rokomari_Cleaned")

Saved in D:\Rokomari_Cleaned

In [39]:
import pandas as pd

page_views = pd.read_csv("page_views.csv")
print(page_views.head(10))

  session_id product_id     category            timestamp
0     S00001      P0033         Baby  2025-09-01 14:20:00
1     S00001      P0263         Baby  2025-09-04 17:50:00
2     S00001      P0160         Food  2025-09-04 14:31:00
3     S00001      P0197         Food  2025-09-04 23:34:00
4     S00002      P0016         Baby  2025-09-01 07:46:00
5     S00002      P0155         Baby  2025-09-04 01:46:00
6     S00003      P0098  Electronics  2025-09-06 18:42:00
7     S00003      P0287         Food  2025-09-02 04:05:00
8     S00003      P0239         Food  2025-09-01 12:49:00
9     S00004      P0017         Food  2025-09-05 19:49:00

In [40]:
import pandas as pd

page_views = pd.read_csv("page_views.csv")

print("Total rows:", page_views.shape[0])
print("Total columns:", page_views.shape[1])

print("\nColumn types:")
print(page_views.dtypes)

print("\nNull values:")
print(page_views.isnull().sum())

print("\nAny null values?")
print("Yes" if page_views.isnull().any().any() else "No")

print("\nDuplicate rows:")
print(page_views.duplicated().sum())

print("\nMessy / weird words:")
for col in page_views.columns:
    if page_views[col].dtype == "object":
        print(f"\nColumn: {col}")
        print(page_views[col].astype(str).str.strip().value_counts().head(10))

Total rows: 6024
Total columns: 4

Column types:
session_id    str
product_id    str
category      str
timestamp     str
dtype: object

Null values:
session_id    0
product_id    0
category      0
timestamp     0
dtype: int64

Any null values?
No

Duplicate rows:
0

Messy / weird words:

In [41]:
import pandas as pd

page_views = pd.read_csv("page_views.csv")

page_views["page_view_date"] = pd.to_datetime(page_views["timestamp"]).dt.date
page_views["page_view_time"] = pd.to_datetime(page_views["timestamp"]).dt.strftime("%I:%M %p")

page_views = page_views.drop(columns=["timestamp"])

print(page_views.head())

  session_id product_id category page_view_date page_view_time
0     S00001      P0033     Baby     2025-09-01       02:20 PM
1     S00001      P0263     Baby     2025-09-04       05:50 PM
2     S00001      P0160     Food     2025-09-04       02:31 PM
3     S00001      P0197     Food     2025-09-04       11:34 PM
4     S00002      P0016     Baby     2025-09-01       07:46 AM

In [43]:
total_rows = page_views.shape[0]
total_unique_session_id = page_views["session_id"].nunique()

print("Total rows:", total_rows)
print("Total unique session_id:", total_unique_session_id)

Total rows: 6024
Total unique session_id: 2000

In [44]:
page_views.to_csv(r"D:\Rokomari_Cleaned\page_views_cleaned.csv", index=False)
print("Saved in D:\\Rokomari_Cleaned")

Saved in D:\Rokomari_Cleaned

<span style="font-size: 24px;">Data Cleaning End Here</span>